### ISSUE TITLE
Add tests for tasks logic and model

### ISSUE THREAD

**Issue by zxjtan** [CS2103-AY1819S1-T09-1/main#36]

**Comment by JayPeeTeeDee** [comment]
Shifted to v1.3

**Comment by JayPeeTeeDee** [comment]
Shifted to v1.4

**Comment by indocomsoft** [comment]
@zxjtan bump?

**Comment by zxjtan** [comment]
Logic
- [ ] Add AddCommandTest
- [ ] Add AddCommandParserTest
- [ ] Add AppParserTest
- [ ] Add TasksParserTest

Model
- [ ] Add TaskTest
- [ ] Add NameTest
- [ ] Add DateTimeTest

Integration
- [ ] Add AddCommandIntegrationTest

**Comment by zxjtan** [comment]
Adequate coverage across the different components achieved.
