### ISSUE TITLE
Mark unimplemented features as coming in v2

### ISSUE THREAD

**Issue by indocomsoft** [CS2103-AY1819S1-T09-1/main#79]

**Comment by indocomsoft** [comment]
@tuesmiddt Can I mark this as resolved since you marked some other calendar commands as coming in v2?

**Comment by tuesmiddt** [comment]
The calendar commands are marked. I think non-calendar commands are all implemented. Can you take a quick look at the rest?

**Comment by indocomsoft** [comment]
During my revamp of UG, I think all other features are implemented by v1.4. So I'm closing this.
